config/routes.rb
GigHub::Application.routes.draw do

  opinio_model

  match 'auth/:provider/callback' => 'authentications#create'

  resources :authentications

  get "welcome/home"

  resources :events do
    opinio
  end

  get "profiles/show"

  devise_scope :user do
    get '/register', to: 'devise/registrations#new', :as => :register
    get '/login', to: 'devise/sessions#new', :as => :login
    get '/logout', to: 'devise/sessions#destroy', :as => :logout
  end

  devise_for :users, skip: [:session]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :statuses do
    opinio
  end

  get 'feed', to: 'statuses#index', :as => :feed

  get '/:id', to: 'profiles#show', :as => :profile

  resources :user_event_attendances

  root :to => 'welcome#home'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.order('created_at desc').all
      render action: :show
      @user_event_attendances = @user.user_event_attendances.all
    else
      render file: 'public/404', status: 404, format: [:html]
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class="page-header">
  <h1><%= @user.full_name %></h1>
</div>

<% if signed_in? %>
<div id="friend-status">
  <% if current_user.friends.include?(@user) || current_user.pending_friends.include?(@user) %>
    <%= link_to "Edit Friendship", edit_user_friendship_path(friend_id: @user), class: 'btn' %>
  <% else %>
    <%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: 'btn', id: "add-friendship", data: { friend_id: @user.to_param } %>
  <% end %>
</div>
<% end %>

<% if @statuses %>
    <h3>Statuses</h3>
    <% @statuses.each do |status| %>
    <div class="well span8">
      <%= status.content %>
      <hr />
      <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
    </div>
    <% end %>
<% end %>

<% if @user_event_attendances %>
    <h3>Upcoming Events</h3>
    <% @user_event_attendances.each do |event| %>
        <div class="well span8">
          <%= event.name %>
        </div>
    <% end %>
<% end %>