config/routes.rb
GigHub::Application.routes.draw do

  opinio_model

  match 'auth/:provider/callback' => 'authentications#create'

  resources :authentications

  get "welcome/home"

  resources :events do
    opinio
  end

  get "profiles/show"

  devise_scope :user do
    get '/register', to: 'devise/registrations#new', :as => :register
    get '/login', to: 'devise/sessions#new', :as => :login
    get '/logout', to: 'devise/sessions#destroy', :as => :logout
  end

  devise_for :users, skip: [:session]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :statuses do
    opinio
  end

  get 'feed', to: 'statuses#index', :as => :feed

  get '/:id', to: 'profiles#show', :as => :profile

  resources :user_event_attendances

  root :to => 'welcome#home'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :content, :name, :picture

  has_many :users, :through => :user_event_attendances
  has_many :user_event_attendances

  has_attached_file :picture #, styles: { large: "800x800", medium: "260x180>", thumb: "80x80#" }

  opinio_subjectum

  def self.search(search_query)
    if search_query
      find(:all,:conditions => ['name LIKE ?', "%#{search_query}%"])
    else
      find(:all)
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]

  # GET /events
  # GET /events.json
  def index
    @events = Event.search(params[:search_query])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = current_user.events.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="well">
  <%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :content %>
  </div>

  <div>
    <%= f.input :picture, as: :file %>
    <% if f.object.picture? %>
        <%= image_tag f.object.picture.url %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="page-header">
  <h1>Events</h1>
</div>

<%= link_to "Create A New Event", new_event_path, class: "btn btn-success" %>

<hr />

<%= form_tag events_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search_query, params[:search_query] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>

<hr />

<% @events.each do |event| %>
  <div class="status">
    <div class="row">
      <div class="span1">
        <%= image_tag event.picture.url(:thumb) %>
      </div>
      <div class="span7">
        <strong><%= event.name %></strong>
        <div class="meta">
          <%= link_to time_ago_in_words(event.created_at) + " ago", event %> |
          <span class="admin">
            <%= link_to "Show", event_path(event) %> |
            <%= link_to "Edit", edit_event_path(event) %> |
            <%= link_to "Delete",
                event,
                method: :delete,
                data: {
                confirm: "Are you sure you want to delete this event?"
                } %>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="well">
    <p id="notice"><%= notice %></p>

    <%= link_to "Attend Event", new_user_event_attendance_path(event_id: @event), class: 'btn' %>

    <div>
        <%= image_tag @event.picture %>
    </div>

    <p>
        <b>Name:</b>
        <%= @event.name %>
    </p>

    <p>
        <strong>Content:</strong>
        <%= @event.content %>
    </p>

    <%= comments_for @event, :limit => 10 %>

    <%= link_to 'Edit', edit_event_path(@event) %> |
    <%= link_to 'Back', events_path %>

</div>