config/routes.rb
GigHub::Application.routes.draw do

  opinio_model

  match 'auth/:provider/callback' => 'authentications#create'

  resources :authentications

  get "welcome/home"

  resources :events do
    opinio
  end

  get "profiles/show"

  devise_scope :user do
    get '/register', to: 'devise/registrations#new', :as => :register
    get '/login', to: 'devise/sessions#new', :as => :login
    get '/logout', to: 'devise/sessions#destroy', :as => :logout
  end

  devise_for :users, skip: [:session]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :statuses do
    opinio
  end

  get 'feed', to: 'statuses#index', :as => :feed

  get '/:id', to: 'profiles#show', :as => :profile

  resources :user_event_attendances

  root :to => 'welcome#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GigHub</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "GigHub", root_path, { :class => "brand" } %>
          <ul class="nav">
          <% if user_signed_in? %>
            <li><%= link_to "Discussions", feed_path %></li>
            <li><%= link_to "All Events", events_path %></li>
          <% end %>
          </ul>

          <ul class="nav pull-right">

            <% if user_signed_in? %>
                <li><%= link_to "Upcoming Events", user_event_attendances_path %></li>
                <li><%= link_to "Friends", user_friendships_path %></li>
                <li><%= link_to "Profile", profile_path(current_user) %></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Logout", logout_path %></li>
            <% else %>
                <li><%=  link_to "Register", register_path %></li>
                <li><%=  link_to "Log In", login_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <% flash.each do |type, message| %>
          <div class="alert <%= flash_class type %>">
            <button class="close" data-dismiss="alert">x</button>
            <%= message %>
          </div>
      <% end %>

      <%= yield %>
    </div>

</body>
</html>